name: Ariel Rodriguez, Software Engineer
highlighter: pygments
permalink: /articles/:title/
exclude: [arielsvn.sublime-project, arielsvn.sublime-workspace]
url: http://arielsvn.github.io
include: ['_pages']
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]